# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

react_native_path = '../node_modules/react-native'

target 'alphaleo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for alphaleo
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging,
    'BatchedBridge',
    'RCTImage'
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  
  pod 'Firebase/Core'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
#  pod 'Firebase/AdMob'
#  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
##  pod 'Firebase/Crash'
  pod 'Firebase/Database'
#  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
#  pod 'Firebase/RemoteConfig'
#  pod 'Firebase/Storage'

  target 'alphaleoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'alphaleoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
